clear, clc
c = 299792458;                            % Speed of light
e = 1.6021766208e-19;                     % Elementary charge
h = 6.626070040e-34;                      % Planck's constant
hb = h/(2*pi);                            % 
k = 1.38064852e-23;                       % Boltzmann's constant
NA = 6.022140857e23;                      % Avogadro's constant
R = NA*k;                                 % Gas constant
F = NA*e;                                 % Faraday's constant
m_e = 9.10938356e-31;                     % Electron mass
m_p = 1.672621898e-27;                    % Proton mass
m_n = 1.674927471e-27;                    % Neutron mass
m_u = 1.660539040e-27;                    % Atomic mass constant
mu_0 = (4*pi)*1e-7;                       % Vacuum permeability
eps_0 = 1/(mu_0*c^2);                     % Vacuum permittivity
peps_0 = 4*pi*eps_0;                      % 4Pi times Vacuum permittivity
mu_B = (e*hb)/(2*m_e);                    % Bohr magneton
mu_N = (e*hb)/(2*m_p);                    % Nuclear magneton
mu_p = 1.4106067873;                      % Proton magnetic moment
g_e = 2.00231930436182;                   % Electron g factor 
gam_e = -(g_e*e)/(2*m_e);                 % Electron magnetogyric ratio
gam_p = (2*mu_p)/hb;                      % Proton magnetogyric ratio
a0 = (4*pi*eps_0*hb^2)/(e^2*m_e);         % Bohr radius
R_inf = (m_e*e^4)/(8*(h^3)*c*(eps_0^2));  % Ryderg's constant
hcR_inf = (h*c*R_inf)/(e);                % 
alfa = mu_0*e^2*c/(2*h);                  % Fine-structure constant
c_2 = h*c/k;                              % Second radiation constant
sigma = (2*pi^5*k^4)/(15*h^3*c^2);        % Stefan-Boltzmann constant
g = 9.80665;                              % Standard acceleration
G = 6.67408e-11;                          % Gravitational constant